sudo: false
language: php
cache:
  directories:
    - vendor
notifications:
  email: false
php:
  - '7.2'
before_script:
  - composer install
script:
  - vendor/bin/phpunit
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
